### ISSUE TITLE
TASK-25: E2E 테스트 구현

### ISSUE THREAD

**Issue by serithemage** [Hands-On-Vibe-Coding/realworld-vibe-coding#25]
## Description
Playwright를 이용한 전체 사용자 플로우 테스트를 구현합니다.

## Background
실제 사용자 시나리오를 검증하기 위한 End-to-End 테스트가 필요합니다. 회원가입부터 게시글 작성, 댓글 작성까지의 전체 플로우를 테스트해야 합니다.

## Acceptance Criteria
- [ ] 사용자 회원가입/로그인 플로우 테스트
- [ ] 게시글 작성/수정/삭제 플로우 테스트
- [ ] 댓글 작성/삭제 플로우 테스트
- [ ] 프로필 조회 및 팔로우 플로우 테스트
- [ ] 게시글 좋아요 플로우 테스트
- [ ] 반응형 디자인 테스트 (모바일, 태블릿)
- [ ] 접근성 테스트
- [ ] 크로스 브라우저 테스트 (Chrome, Firefox, Safari)
- [ ] 성능 테스트 (페이지 로딩 시간)
- [ ] CI/CD 파이프라인에 E2E 테스트 통합

### Test Structure
```
e2e/
├── tests/
│   ├── auth/
│   │   ├── login.spec.ts
│   │   └── register.spec.ts
│   ├── articles/
│   │   ├── create-article.spec.ts
│   │   ├── edit-article.spec.ts
│   │   └── favorite-article.spec.ts
│   ├── comments/
│   │   └── comment-flow.spec.ts
│   ├── profile/
│   │   └── follow-user.spec.ts
│   └── accessibility/
│       └── a11y.spec.ts
├── fixtures/
│   ├── users.json
│   └── articles.json
├── utils/
│   ├── auth-helper.ts
│   └── db-helper.ts
├── playwright.config.ts
└── package.json
```

### Test Examples
```typescript
// e2e/tests/auth/login.spec.ts
import { test, expect } from '@playwright/test'

test.describe('User Authentication', () => {
  test('should login with valid credentials', async ({ page }) => {
    await page.goto('/')
    await page.click('text=Sign in')
    
    await page.fill('[placeholder="Email"]', 'test@example.com')
    await page.fill('[placeholder="Password"]', 'password123')
    await page.click('button[type="submit"]')
    
    await expect(page).toHaveURL('/')
    await expect(page.locator('text=Your Feed')).toBeVisible()
  })
  
  test('should show error for invalid credentials', async ({ page }) => {
    await page.goto('/login')
    
    await page.fill('[placeholder="Email"]', 'invalid@example.com')
    await page.fill('[placeholder="Password"]', 'wrongpassword')
    await page.click('button[type="submit"]')
    
    await expect(page.locator('text=Invalid credentials')).toBeVisible()
  })
})

// e2e/tests/articles/create-article.spec.ts
import { test, expect } from '@playwright/test'
import { loginAsUser } from '../../utils/auth-helper'

test.describe('Article Management', () => {
  test.beforeEach(async ({ page }) => {
    await loginAsUser(page, 'testuser@example.com', 'password123')
  })
  
  test('should create new article', async ({ page }) => {
    await page.goto('/editor')
    
    await page.fill('[placeholder="Article Title"]', 'Test Article')
    await page.fill('[placeholder="Article Description"]', 'This is a test article')
    await page.fill('[placeholder="Article Body"]', 'Article content goes here')
    await page.fill('[placeholder="Enter tags"]', 'test,playwright')
    
    await page.click('text=Publish Article')
    
    await expect(page).toHaveURL(/\/article\/test-article/)
    await expect(page.locator('h1')).toContainText('Test Article')
  })
})
```

### Playwright Configuration
```typescript
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test'

export default defineConfig({
  testDir: './e2e/tests',
  fullyParallel: true,
  forbidOnly: \!\!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  
  use: {
    baseURL: 'http://localhost:5173',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure'
  },
  
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] }
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] }
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] }
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] }
    }
  ],
  
  webServer: [
    {
      command: 'npm run dev',
      url: 'http://localhost:5173',
      reuseExistingServer: \!process.env.CI
    },
    {
      command: 'cd ../backend && make dev',
      url: 'http://localhost:8080/health',
      reuseExistingServer: \!process.env.CI
    }
  ]
})
```

### CI Integration
```yaml
# .github/workflows/e2e.yml
name: E2E Tests
on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      - name: Run E2E tests
        run: npm run test:e2e
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
```

## Dependencies
- TASK-23: 백엔드 유닛 테스트 구현
- TASK-24: 프론트엔드 테스트 구현

## Estimated Time
8시간
