### ISSUE TITLE
TASK-28: 프로덕션 배포 및 모니터링

### ISSUE THREAD

**Issue by serithemage** [Hands-On-Vibe-Coding/realworld-vibe-coding#27]
## Description
실제 운영 환경 배포 및 모니터링 설정을 완료합니다.

## Background
구축된 인프라에 애플리케이션을 배포하고, 운영 중 발생할 수 있는 문제들을 모니터링할 수 있는 시스템이 필요합니다.

## Acceptance Criteria
- [ ] 프로덕션 환경 애플리케이션 배포
- [ ] 도메인 연결 및 SSL 인증서 설정
- [ ] CloudWatch 대시보드 구성
- [ ] 로그 수집 및 분석 설정
- [ ] 알람 및 알림 설정
- [ ] 성능 모니터링 (APM)
- [ ] 에러 트래킹 및 알림
- [ ] 백업 및 복구 절차 구현
- [ ] 보안 모니터링 설정
- [ ] 사용자 접근 테스트 및 검증
- [ ] 운영 가이드 문서 작성

### Deployment Process
```bash
# 1. Docker 이미지 빌드 및 푸시
docker build -t realworld-backend:latest ./backend
docker tag realworld-backend:latest $ECR_URI/realworld-backend:latest
docker push $ECR_URI/realworld-backend:latest

docker build -t realworld-frontend:latest ./frontend
docker tag realworld-frontend:latest $ECR_URI/realworld-frontend:latest
docker push $ECR_URI/realworld-frontend:latest

# 2. ECS 서비스 업데이트
aws ecs update-service \
  --cluster realworld-cluster \
  --service realworld-backend \
  --force-new-deployment

aws ecs update-service \
  --cluster realworld-cluster \
  --service realworld-frontend \
  --force-new-deployment

# 3. 배포 상태 확인
aws ecs describe-services \
  --cluster realworld-cluster \
  --services realworld-backend realworld-frontend
```

### Monitoring Configuration
```yaml
# cloudwatch-config.yml
version: '1'
agent:
  metrics_collection_interval: 60
  run_as_user: root
metrics:
  namespace: RealWorld/Application
  metrics_collected:
    cpu:
      measurement:
        - cpu_usage_idle
        - cpu_usage_iowait
        - cpu_usage_user
        - cpu_usage_system
      metrics_collection_interval: 60
    disk:
      measurement:
        - used_percent
      metrics_collection_interval: 60
      resources:
        - "*"
    diskio:
      measurement:
        - io_time
      metrics_collection_interval: 60
      resources:
        - "*"
    mem:
      measurement:
        - mem_used_percent
      metrics_collection_interval: 60
    netstat:
      measurement:
        - tcp_established
        - tcp_time_wait
      metrics_collection_interval: 60
logs:
  logs_collected:
    files:
      collect_list:
        - file_path: /var/log/application/*.log
          log_group_name: /aws/ecs/realworld-backend
          log_stream_name: '{instance_id}'
```

### Health Checks
```go
// backend health check endpoint
func (h *HealthHandler) Check(w http.ResponseWriter, r *http.Request) {
    status := map[string]interface{}{
        "status": "ok",
        "timestamp": time.Now().Unix(),
        "version": os.Getenv("APP_VERSION"),
        "database": h.checkDatabase(),
        "memory": h.getMemoryUsage(),
    }
    
    w.Header().Set("Content-Type", "application/json")
    json.NewEncoder(w).Encode(status)
}
```

### Alert Configuration
```typescript
// monitoring/alerts.ts
const alerts = [
  {
    name: 'High Error Rate',
    metric: 'HTTP 5xx errors',
    threshold: 10,
    period: '5 minutes',
    action: 'Send to Slack + PagerDuty'
  },
  {
    name: 'High Response Time',
    metric: 'Average response time',
    threshold: '3 seconds',
    period: '5 minutes',
    action: 'Send to Slack'
  },
  {
    name: 'Database Connection Issues',
    metric: 'Database connection errors',
    threshold: 5,
    period: '2 minutes',
    action: 'Send to PagerDuty'
  },
  {
    name: 'High CPU Usage',
    metric: 'ECS CPU utilization',
    threshold: '80%',
    period: '10 minutes',
    action: 'Send to Slack'
  }
]
```

### Backup Strategy
```bash
#\!/bin/bash
# backup-script.sh

# Database backup
pg_dump $DATABASE_URL > backup_$(date +%Y%m%d_%H%M%S).sql

# Upload to S3
aws s3 cp backup_*.sql s3://realworld-backups/database/

# Keep only last 30 days of backups
aws s3 ls s3://realworld-backups/database/ | \
  awk '{print $4}' | \
  sort | \
  head -n -30 | \
  xargs -I {} aws s3 rm s3://realworld-backups/database/{}
```

### Performance Testing
```javascript
// load-test.js using k6
import http from 'k6/http'
import { check, sleep } from 'k6'

export let options = {
  vus: 10, // 10 virtual users
  duration: '30s',
}

export default function () {
  // Test homepage
  let response = http.get('https://realworld.example.com/')
  check(response, {
    'homepage loads': (r) => r.status === 200,
    'response time < 3s': (r) => r.timings.duration < 3000,
  })
  
  // Test API
  response = http.get('https://api.realworld.example.com/api/articles')
  check(response, {
    'API responds': (r) => r.status === 200,
    'API response time < 1s': (r) => r.timings.duration < 1000,
  })
  
  sleep(1)
}
```

### Operation Runbook
```markdown
# RealWorld Application Operations Runbook

## Deployment Procedure
1. Run tests locally: `make test`
2. Create PR and ensure CI passes
3. Merge to main branch
4. Monitor automatic deployment
5. Verify health checks pass
6. Perform smoke tests

## Troubleshooting Guide
### High Error Rate
1. Check CloudWatch logs
2. Verify database connectivity
3. Check ECS service health
4. Roll back if necessary

### Performance Issues
1. Check CloudWatch metrics
2. Monitor database performance
3. Scale ECS tasks if needed
4. Check CDN cache hit rate

## Contact Information
- On-call Engineer: oncall@company.com
- Slack Channel: #realworld-ops
- PagerDuty: realworld-service
```

## Dependencies
- TASK-26: GitHub Actions CI/CD 파이프라인
- TASK-27: AWS ECS 인프라 구축

## Estimated Time
6시간
