### ISSUE TITLE
TASK-04: Docker 개발 환경 구축

### ISSUE THREAD

**Issue by serithemage** [Hands-On-Vibe-Coding/realworld-vibe-coding#5]
## Description
Docker Compose를 이용한 통합 개발 환경을 구축합니다.

## Background
프론트엔드와 백엔드를 통합적으로 개발할 수 있는 Docker 환경이 필요합니다. 로컬 개발 시 일관된 환경을 제공하고, 데이터베이스 포함 전체 스택을 쉽게 실행할 수 있어야 합니다.

## Acceptance Criteria
- [ ] docker-compose.yml 파일 생성
- [ ] 백엔드용 Dockerfile 생성
- [ ] 프론트엔드용 Dockerfile 생성
- [ ] SQLite 데이터베이스 볼륨 설정
- [ ] 네트워크 설정 및 포트 매핑
- [ ] 개발 환경 변수 설정
- [ ] make dev 명령어로 전체 스택 실행 가능
- [ ] 핫 리로드 기능 동작 확인

### Docker Compose Structure
```yaml
version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development
  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
```

## Dependencies
- TASK-01: 백엔드 프로젝트 구조 설정
- TASK-02: 프론트엔드 프로젝트 구조 설정

## Estimated Time
4시간
